### ISSUE TITLE
Headless installation - display error

### ISSUE THREAD

**Issue by Bigun** [jasonmpittman/cowrie-log-analyzer#1]
I have the dependencies installed and the logs in place.  I run python3 client.py and get an error:

`cowrie@SSHHoneypot-ct:~/cowrie-log-analyzer$ python3 client.py 
Traceback (most recent call last):
  File "/home/cowrie/cowrie-log-analyzer/client.py", line 38, in <module>
    main()
  File "/home/cowrie/cowrie-log-analyzer/client.py", line 24, in main
    root = tk.Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

I'm assuming this requires X to work?  If it does, a feature request is to somehow display the data in plain text.

**Comment by jasonmpittman** [comment]
Thanks for your comment @Bigun .Yes, a WM environment is required for the tkinter module to work correctly. I hear the suggestion for a CLI option though and can look at adding a plain text display to the shell.
